import type { ComponentClass } from '@vworlds/vecs';
import {
  Arc,
  AsteroidView,
  Drawable,
  ExplosionView,
  FillStyle,
  FilledRect,
  GameStateView,
  HealthView,
  PickupView,
  PlayerShip,
  Position,
  ProjectileView,
  Rotation,
  Shape,
  ShieldView,
  StrokeStyle,
  WeaponView,
} from '../components';

export const NETWORK_COMPONENTS = [
  Position,
  Rotation,
  Drawable,
  StrokeStyle,
  FillStyle,
  Shape,
  Arc,
  FilledRect,
  PlayerShip,
  AsteroidView,
  ProjectileView,
  PickupView,
  HealthView,
  ShieldView,
  WeaponView,
  GameStateView,
  ExplosionView,
] satisfies readonly ComponentClass[];
