export const WORLD_WIDTH = 1024;
export const WORLD_HEIGHT = 768;
export const CLIENT_ENTITY_ID_START = 1_000_000;

export const GAME_CONFIG = {
  ALIEN_SPAWN_MIN_WAIT: 10000,
  ALIEN_SPAWN_MAX_WAIT: 20000,
  ALIEN_CAP: 3,

  SHIELD_SPAWN_MIN_WAIT: 8000,
  SHIELD_SPAWN_MAX_WAIT: 21000,
  LASER_SPAWN_MIN_WAIT: 30000,
  LASER_SPAWN_MAX_WAIT: 70000,
  AURA_SPAWN_MIN_WAIT: 45000,
  AURA_SPAWN_MAX_WAIT: 99000,
  ROCKET_SPAWN_MIN_WAIT: 50000,
  ROCKET_SPAWN_MAX_WAIT: 110000,
  BOOMERANG_SPAWN_MIN_WAIT: 50000,
  BOOMERANG_SPAWN_MAX_WAIT: 110000,
  HEALTH_SPAWN_MIN_WAIT: 18000,
  HEALTH_SPAWN_MAX_WAIT: 42000,

  SHIELD_PICKUP_TTL_FRAMES: 720,
  LASER_PICKUP_TTL_FRAMES: 720,
  AURA_PICKUP_TTL_FRAMES: 720,
  ROCKET_PICKUP_TTL_FRAMES: 720,
  BOOMERANG_PICKUP_TTL_FRAMES: 720,
  HEALTH_PICKUP_TTL_FRAMES: 720,
} as const;

export const ENTITY_CONFIG = {
  BULLET: {
    SPEED: 7,
    LIFE: 100,
    DAMAGE: 10,
  },
  ASTEROID: {
    SPEED_FACTOR: 4,
  },
  POWERUP: {
    SPEED_FACTOR: 1,
    RADIUS: 15,
  },
  ALIEN: {
    RADIUS: 15,
    SPEED_FACTOR: 2,
    SHOOT_COOLDOWN_BASE: 60,
    SHOOT_COOLDOWN_RANGE: 40,
    TARGET_DIST_MAX: 400,
    ASTEROID_AVOID_DIST: 60,
    MAX_HP: 20,
  },
  ROCKET: {
    SPEED: 5,
    LIFE: 400,
    STRAIGHT_FRAMES: 30,
    HOME_RANGE: 250,
    TURN_RATE: 0.08,
    SHOT_COUNT: 5,
    DAMAGE: 20,
  },
  BOOMERANG: {
    SPEED: 19,
    MAX_SPEED: 13,
    PULL: 0.3,
    LIFE: 600,
    SPIN: 0.28,
    RADIUS: 7,
    DAMAGE: 15,
    MAX_SHOTS: 20,
    ARM_DISTANCE: 30,
  },
  EXPLOSION: {
    LIFE_FRAMES: 30,
  },
  SHIP: {
    RADIUS: 12,
    FRICTION: 0.98,
    ROTATION_SPEED: 0.07,
    THRUST_POWER: 0.2,
    SHOOT_COOLDOWN: 15,
    MAX_HP: 100,
    LASER_SHOT_COUNT: 10,
    LASER_TIMER: 200,
    AURA_SHOT_COUNT: 10,
    SHIELD_DURATION: 2400,
    HEALTH_BAR_TIMER: 60,
  },
} as const;

export const SCORING = {
  ASTEROID_BASE: 10,
  ALIEN: 100,
  SHIELD: 50,
  LASER: 75,
  AURA: 75,
  ROCKET: 75,
  BOOMERANG: 75,
  HEALTH_SMALL: 50,
  HEALTH_LARGE: 75,
} as const;

export const SHIELD_DAMAGE = {
  BULLET: 300,
  ALIEN_BODY: 600,
  ASTEROID: 300,
} as const;

export const CAT_PLAYER = 1 << 0;
export const CAT_ASTEROID = 1 << 1;
export const CAT_PLAYER_BULLET = 1 << 2;
export const CAT_ENEMY_BULLET = 1 << 3;
export const CAT_ENEMY = 1 << 4;
export const CAT_PICKUP = 1 << 5;
export const CAT_BOOMERANG = 1 << 6;
